
all:
	gcc -c collisionDetection.c -lm -g -Wall
	gcc -o collisionDetection_duplicated collisionDetection_duplicated.c collisionDetection.o -lm -g -Wall

clean:
	rm *.o collisionDetection collisionDetection_duplicated

